services:
  api:
    container_name: api
    image: journey.api
    build:
      context: .
      dockerfile: src/Journey.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_HOST: host.docker.internal
    networks:
      - journey
  
  db: 
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reallyStrongPwd123
      POSTGRES_DB: journey
    networks:
      - journey

networks:
  journey:
    driver: bridge
    
