services:
  api:
    container_name: api.aws
    image: journey.api
    build:
      context: .
      dockerfile: src/Journey.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres-1.cnmgy8a06r5x.us-east-1.rds.amazonaws.com