apiVersion: apps/v1
kind: Deployment

metadata:
  name: journey-deployment
  labels:
    app: journey
    
spec:
  replicas: 5
  selector:
    matchLabels:
      app: journey
  template:
    metadata:
      labels:
        app: journey
    spec:
      containers:
        - name: api-journey
          image: damasc84/journey.api:e5e5c32
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: db_host
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              cpu: "600m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"