name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        
    - name: Login into container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build docker image
      run: docker build -t damasc84/journey.api:${{ steps.generate_sha.outputs.sha }} -f src/Journey.Api/Dockerfile .

    - name: Push image to container registry
      run: |
        docker push damasc84/journey.api:${{ steps.generate_sha.outputs.sha }}
        docker tag damasc84/journey.api:${{ steps.generate_sha.outputs.sha }} damasc84/journey.api:latest
        docker push damasc84/journey.api:latest
        